#---------------------global plotting params---------------------
global guidefontsize::Int = 28
global legendfontsize::Int = 14
global tickfontsize::Int = 16
global annotation_fontsize::Int = 22 
global linecolor=:gray10
global reduced_right_margin = 2Plots.mm
global reduced_left_margin = 4Plots.mm
global left_margin = 6Plots.mm
global reduced_top_margin = -6Plots.mm
global reduced_top_margin_sm = -2Plots.mm
global top_margin = 5Plots.mm
global colfig_size = (1000,1200)
global bigfig_size = (1500,1200)
global marker_size_colored = 12 
global ylims_od = (-0.2,1.45)
global inset_box = bbox(0.63,-0.05,0.2,0.3)
global subfigure_annotation_pos_two_col = (-0.35,1.0)
global subfigure_annotation_pos_two_col_alter_layout = (-0.3,1.0)
global subfigure_annotation_pos_two_col_inner = (-0.13,1.0)
global subfigure_annotation_pos_one_adjusted = (-0.2,1.0)
global subfigure_annotation_pos_one_col = (-0.15,1.0)
global subfigure_annotation_pos_bigfig_inner = (-0.1,1.0)
global subfigure_annotation_pos_alter = (0.02,1.0)
global inset_tickfontsize = 14
global legend_position = (0.6,0.7)
global marker_shapes = [:rect,:star5,:circle,:diamond]
global marker_colors = [:red,:blue,:green,:orange]
global wl_colors = [:red,:green,:orange]
global alphas = [0.4:0.2:1.0;]
global marker_pos_henon = [0.005,0.02,0.02]
global marker_pos_log = [0.007,0.02,0.02]
global histogram_alpha = 0.5
global nr_bins = 40
global common_y_lims = (0.0,0.075)
global curve_lw = 2
global h_top_henon::Float64 = 0.465
global λ_henon::Float64 = 0.42
global ms_od_henon = 0.5
global ma_od_henon = 0.9
global ms_od_logistic = 0.3
global ma_od_logistic = 0.8

global ensemble::Int64 = 10^3 
global N_steps::Int64 = 500
gauss(x,μ,σ) = 1/(σ*sqrt(2π)) * exp(-(x - μ)^2/(2σ^2)) 